# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mrizhakov <mrizhakov@student.42.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/30 17:37:29 by mrizhakov         #+#    #+#              #
#    Updated: 2024/02/03 00:08:28 by mrizhakov        ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

Megaphone: Megaphone.o
	c++ Megaphone.o -o Megaphone

Megaphone.o: Megaphone.cpp
	c++ -c Megaphone.cpp

clean:
	rm *.o Megaphone